### ISSUE TITLE
Table Class Options setting?

### ISSUE THREAD

**Issue by warrichrepos** [ephemer/meteor-reactive-datatables#13]
Thank u for this package. I'm trying to set the class for the data table. I see this is set to "table datatable" in your source. Is there a way to set this in options to get row striping for example?
Apologies if I'm missed this somewhere or if this is something we're expected to modify via meteor dom manipulation. Thanks for any help.

**Comment by ephemer** [comment]
Hi @warrichrepos. This is a part of the standard Datatables API so it's not documented in this repo.

See for example
http://datatables.net/reference/option/stripeClasses

**Comment by ndastur** [comment]
I have just made a pull request to deal with this #33 
The comment above is to set the classes for individual table row stripes. The OP and I want to set the class of the table itself
