### ISSUE TITLE
Update jquery.dataTables.min.js to v1.10.3 or beyond

### ISSUE THREAD

**Issue by rjsmith** [ephemer/meteor-reactive-datatables#17]
Hi,
Just found this repo, looks like a useful wrapper around datatables - thanks!

I'd appreciate it if you could update the included jquery.dataTables.min.js to v1.10.3 or beyond (I think the latest is v1.10.5 at the time of writing?).  I need to use the column().dataSrc() API method which was added in v1.10.3 .

Regards,
Richard

**Comment by ephemer** [comment]
Hi Richard, thanks for your report. Would you consider making a pull request for this? I don't have a lot of time to test whether anything breaks with an updated Datatables version.

Cheers,
Geordie

**Comment by ephemer** [comment]
I just updated the version to the latest 1.10.7 and updated the package on atmosphere
