### ISSUE TITLE
Why do you use if(!data.length) return; in reactive-datatables.js

### ISSUE THREAD

**Issue by buduguru** [ephemer/meteor-reactive-datatables#18]
First of all, thank you for the package.

All worked OK until I needed to include custom search using Session.

1. My dataTableData function returns this:
`Tours.find(Session.get('tourFind')).fetch()`
When template renders that Session is set to {}, so all documents are included in the table - it renders OK.
2. But when I set that Session to another value which causes dataTableData to return different output (I check it in chrome console) - the table does not re-render. 
3. I digged in the package code and deleted `if(!data.length) return;` from reactive-datatables.js - now it works!

So the question is what is the logic under that sentence, why did you include it?
It prevents the table to be re-rendered if the data.length is 0, but why is it important? Maby it need to be changed to if(!data) or smth?

**Comment by ephemer** [comment]
I think I did it to prevent a re-render if the subscription isn't ready yet. I had run into the same problem though and you're right, it makes no sense to have it there in its current form.

**Comment by buduguru** [comment]
Yes. I think it is better to check for subscription in iron router (via `waitOn`) or in `Template.table.onCreate` via new https://docs.meteor.com/#/full/Blaze-TemplateInstance-subscribe
