### ISSUE TITLE
Update atmospherejs overview

### ISSUE THREAD

**Issue by guilhermebruzzi** [ephemer/meteor-reactive-datatables#20]
Hi, the example in https://atmospherejs.com/ephemer/reactive-datatables has the following code:
dataTableData = function () {
    return Meteor.users.find();
};

I don't know why it differs from this Github README, but it should be:
dataTableData = function () {
    return Meteor.users.find().fetch(); // or .map()
};

Without it, the following error occurs:
Exception from Tracker afterFlush function: Cannot read property 'nodeName' of null

Thanks.

**Comment by ephemer** [comment]
Thanks for the heads up, I probably need to push a new version to atmosphere.

**Comment by ephemer** [comment]
Finally got around to updating this, and pushed the latest version of Datatables
