### ISSUE TITLE
The columns name (options) are not reactive

### ISSUE THREAD

**Issue by zilev** [ephemer/meteor-reactive-datatables#21]
I would like the columns name be reactive as the rows behavior. how I can do that???

**Comment by ephemer** [comment]
Hi, sorry about the late response, github seems to notify me for everything except messages about my own repos!

In its current state I would suggest using the datatables api for this:
```
Tracker.autorun(function () {
  var heading = MyReactiveColumnVar.get();
  // see https://datatables.net/reference/api/column().header()
  $("#datatable").dataTable().api().therestofthecallsyouneed
})
```

**Comment by ephemer** [comment]
I'm closing this issue. Did it fix the problem?

**Comment by zilev** [comment]
:+1:
