### ISSUE TITLE
Using iron router functions in before rendering the table data

### ISSUE THREAD

**Issue by gubagu** [ephemer/meteor-reactive-datatables#23]
Howdy ! Great package man thanks !
I run into some puzzle. Is it possible to use the functions of iron router like "pathFor" render  helper and what is the best way to do that ?

Thank in advance! 
Great plugin keep the great work 

Cheerz

**Comment by gubagu** [comment]
After a bit of google-ing trial and error i found how to get pathFor functionality  in your column render function.

       link = Router.routes['category'].path({_id: currentRow._id})

The code above will generate link that you normally generate with {{pathFor 'category'}}

Hope it could save time to someone some time 

Cheerz

**Comment by ephemer** [comment]
Hi I just saw this, glad you figured it out!
