### ISSUE TITLE
Best practice for using DataTable Extensions?

### ISSUE THREAD

**Issue by mrigali** [ephemer/meteor-reactive-datatables#26]
In your experience, what is the best practice to add DataTable Extensions to reactive-datatables?

Is just having the extension's source in a client directory sufficient?

**Comment by ephemer** [comment]
Hi, I haven't used any extensions myself, you'd just have to give it a try with your particular one.

Meteor recommends using the client/compatibility directory to load 3rd party plugins (files there don't get minified or otherwise squashed in the build process)
