### ISSUE TITLE
getting it to work Mangodb

### ISSUE THREAD

**Issue by sali1982** [ephemer/meteor-reactive-datatables#27]
How I can make this work on angular-meteor package?

I have this line: $scope.assets =$meteor.collection(Assets);

I try this: 
  dataTableData = function () {
            return $meteor.collection(Assets);
          };

Does not make my table.

But when I do this:

  dataTableData = function () {
            return [{ title : "TEST"}]
          };

I have my table working....

How I can return my collection so it works?

**Comment by ephemer** [comment]
Hi @sali1982, your function needs to return an Array or an Object (as required by jQuery Datatables), this is why your second example works.

You can't just return a collection, you'd have to do collection.find().fetch()

**Comment by ephemer** [comment]
I'm going to assume you got this working, closing the issue
