### ISSUE TITLE
Select extension not working : "Uncaught TypeError: Cannot read property 'style' of undefined"

### ISSUE THREAD

**Issue by rolivav** [ephemer/meteor-reactive-datatables#32]
I recently migrated from vanilla DataTables to your package, since I needed the rectivity. I just took out jquery.datatables.js and added your package. Now select doesn't work and I don't see why.

I added 4 files to /lib/compatibility:

dataTables.bootstrap.js
dataTables.responsive.js
dataTables.select.js
responsive.bootstrap.min.js

customers.js
```
var optionsObject = {
	responsive: true,
	autoWidth: false,
	columns: [
		{
			title: "<input type='checkbox' id='check-all' name = 'check-all'/>",
			data: "", //if null, datatables will ask for it with an alert
			defaultContent: ""
		},
		{ 
			data: "_id",
			title: "ID",
			defaultContent: "",
			visible: false,
			searchable: false
		},
		{
			data: "Nombre",
			title: "Nombre",
			defaultContent: ""
		},
		{
			data: "email",
			title: "Email",
			defaultContent: ""
		},
		{
			data: "Teléfono",
			title: "Teléfono",
			defaultContent: ""
		},
		{
			data: "Calle",
			title: "Calle",
			defaultContent: ""
		},
		{
			data: "CP",
			title: "CP",
			defaultContent: ""
		},
		{
			data: "Provincia",
			title: "Provincia",
			defaultContent: "" 
		},
		{ //needed for responsive to work properly in reactive-datatables
			data: "",
			title: "",
			defaultContent: ""
		}
  	],
	columnDefs: [
	    {
			orderable: false,
			className: 'select-checkbox',
			targets: 0},
            {
            className: 'control',
            orderable: false,
            targets:   -1
        }],
	select:
	{
		style: 'multi',
		selector: 'td:first-child'
	},	
	responsive: {
            details: {
                type: 'column',
                target: -1
            }
        },
	// order: [[2, 'asc']],
	}
};

dataTableData = function () {
    return Customers.find().fetch(); // or .map()
};

Template.table.helpers({
    reactiveDataFunction: function () {
        return dataTableData;
    },
    optionsObject: optionsObject // see below
});
```
The select boxes appear, but when I try to click on them nothing happens. It should select their rows. If I try to call datatables.rows(0).select() it displays that error on console. 
"Uncaught TypeError: Cannot read property 'style' of undefined"

It is called in this part of the code in dataTable.select.js:

```
function clear( ctx, force )
{
	if ( force || ctx._select.style === 'single' ) {
		var api = new DataTable.Api( ctx );
		
		api.rows( { selected: true } ).deselect();
		api.columns( { selected: true } ).deselect();
		api.cells( { selected: true } ).deselect();
	}
}
```
Any ideas?

**Comment by ephemer** [comment]
@rolivav I've only tested it with the version shipped with the package (and the version that I used to ship with the package). Is there a reason oh can't just use that version instead?

**Comment by rolivav** [comment]
@ephemer which version? I used the one shipped with the package too.

**Comment by ephemer** [comment]
@rolivav sorry, I misunderstood your question. thought you replaced the version of datatables included with the package. Maybe that would be worth trying. I have no experience with the plugins you mentioned so I can't help you debugging this one. If updating the datatables version fixes it then you'd be more than welcome to send a pull request with the newest datatables version (y)

**Comment by rolivav** [comment]
@ephemer oooh you mean select was included in the datatables js in your package? I think I misunderstood your answer actually, I normally divide datatables in different files to ensure I only add js files that I'm positive I'm going to use. If your package includes select I now understand what was going on. What plugins does your js have bundled in?
