### ISSUE TITLE
Buttons 

### ISSUE THREAD

**Issue by goeman** [ephemer/meteor-reactive-datatables#34]
Am I able to incorporate buttons using this package? I am having some difficulty, but maybe I am not seeing something correctly:

I am trying to to define buttons in my options:

var optionsObject = {
	 buttons: [ 'pdf'],
    columns: [{
[...]

Any advice would be appreciated!

Thank you!

**Comment by ephemer** [comment]
Is that a datatables feature? It's new to me. If it's something in an updated version of datatables then we can update the version here. Otherwise you'd have to use a custom render function like in the docs of this repo. Closing this for now

**Comment by jwjordan** [comment]
Did you happen to include buttons support?  It doesn't seem to "just work" by adding the correct options of "dom" and "buttons" per the datatables documentation:

https://datatables.net/reference/button/

It would definitely be an awesome thing to have!

**Comment by ephemer** [comment]
@jwjordan it may be available in a new version of DataTables. I'd be happy to merge a pull request containing an update but I haven't used this package myself in a few years now
