### ISSUE TITLE
passing an array 

### ISSUE THREAD

**Issue by logtomadhu** [ephemer/meteor-reactive-datatables#35]
Hi

Am new to meteor and javascript.

Am having two sets of array , 

1.array which contains a table head.
     ex head: ["Column 1", "Column 2"]

2.nested array contains table data.

   ex data: [["column 1 value", column 2 value"] , ["column 1 value", column 2 value"]  ...]

how can i pass the title and data using this array

Suggest me how to solve this problem?

**Comment by ephemer** [comment]
This is a question for datatables itself, not for the reactive wrapper. I personally don't know how to do what you're asking, I've always used this with objects rather than arrays. I'd recommend you go to the datatables website and look at their documentation and examples
