### ISSUE TITLE
Using Extensions

### ISSUE THREAD

**Issue by Architecty** [ephemer/meteor-reactive-datatables#36]
Ok, I feel a bit silly about this, but how would I bring in extension into this? I assumed that dumping the relevant css and js into the project would be enough to give access, but that doesn't seem to be the case. I'm specifically looking at FixedHeader, but I'm sure with an example for one, I could get the rest working.

**Comment by ephemer** [comment]
Sorry for the late reply, I didn't get email notifications about this repo for a long time (I think I've fixed it now) and seem to have missed a bunch of questions.

Can you provide a link to the extension you were trying to use and preferably a link to a public GitHub repo with an attempt to integrate the extension?

It's possible you just need to put the extension in meteor's "client/compatibility" directory

**Comment by manusharma1** [comment]
Hi @ephemer ,

I would like to integrate datatables editor extension with keytable : https://editor.datatables.net/examples/extensions/keyTable.html

It would be great if you can have this extension (editor) integrated with this your package.

I will also try to check and see if this work with meteor's "client/compatibility" directory as you mentioned in your post.

Thanks and Best Regards,
Manu

**Comment by ephemer** [comment]
Hi @manusharma1 ,

Let me know how you go with the compatibility directory. It's possible we will need to update the datatables version in the package (or better: swap it out so it's independently updatable via npm). Good luck

**Comment by manusharma1** [comment]
Hi @ephemer 

Thanks for your reply, I will try it and get back on this soon.

Thanks and Best Regards,
Manu

**Comment by ephemer** [comment]
Closing this for now, we can re-open it if adding extensions in the compatibility directory doesn't do the trick
