### ISSUE TITLE
Changes to options don't appear upon page reload unless stateSave is set to false

### ISSUE THREAD

**Issue by dkoo761** [ephemer/meteor-reactive-datatables#41]
Hi there,

It would be good to mention in the docs that during development, stateSave should be explicitly set to false in the options so that changes show up in the table upon page refresh. I couldn't figure out why my option changes weren't appearing until I dived into the source code for the package and saw that there was a stateSave option and then read up on how it worked. I'm assuming other devs have had the same issue.

Cheers!
Dave

**Comment by manusharma1** [comment]
Hi @dkoo761 ,

Yes, I agree also few devs like me doesn't know about overriding default options, I recently discovered this similar issue, By default PageLength is 5 and I was not knowing this how to resolve this. I was literally playing up with datatables object using onRendered then I discovered that we can override the default values using OptionsObject

Now I did : 
`pageLength: 100,
columnDefs: [{ 
	targets: '_all',
	defaultContent: ''
}], `

Solved my Issue, Any devs facing similar issues can setup default values in OptionsObject

Please feel free to ping if anyone is facing the same issue, I would be happy to help

Thanks and Best Regards,
Manu`

**Comment by ephemer** [comment]
Hi Dave, I never ran into this issue myself. What exactly were you expecting to see happen and what happened in its place?

**Comment by dkoo761** [comment]
Hi @ephemer,

During development, I was modifying various options of my datatable (such as order, lengthMenu, and pageLength) but after the initial round of options modifications, the subsequent options modifications weren't showing up in the table, even after refreshing the page. It turns out this was due to the stateSave option being set to true which was caching the datatable options in the browser's LocalStorage and loading them from the cache rather than using the latest version from my datatable definition.

Here's the line of code that sets the stateSave property: https://github.com/ephemer/meteor-reactive-datatables/blob/754b68ceadf1874c56b593ecaf5d017b6361db94/reactive-datatables.js#L7

After setting stateSave to false in my table definition and reloading the page, my modified datatables options then were reflected in my table.

More info: https://datatables.net/reference/option/stateSave

**Comment by ephemer** [comment]
That's a good point. I never ran into that because I didn't change those options I guess.

To me it seems very strange that table options even get saved in the datatables state at all, so I think best solution would be to just not save those keys in state. In that link you sent it looks like there's a way to only save parts of the serialised state. I'd gladly accept a pull request that does that.

Of course you could also argue that saveState shouldn't be true by default. I don't know. To be honest I haven't used this package myself in over a year. So I'd also accept a pull request that just sets it to not saveState by default. That would probably have to be a major version number change though (also fine by me)

**Comment by dkoo761** [comment]
I don't think there's a way to specify what part of the state to save. At least I didn't see that in the dataTables "stateSave" link above.

So I think the simplest solution is just to update the README to add something like this:

"**Important**: during development, `stateSave` should be explicitly set to `false` in the options so that changes to options show up in the table upon page refresh."

**Comment by ephemer** [comment]
I added a couple of lines of comment in the sample code. Feel free to submit a pull request if you think it should be changed or expanded. Closing this for now
