### ISSUE TITLE
Datatable footer

### ISSUE THREAD

**Issue by Barulin** [ephemer/meteor-reactive-datatables#43]
Hi everyone!

Is there any way to put a `<tfoot>` tag inside a datatable instance?

I'm looking for possibility of making footer summaries like in this example: https://datatables.net/examples/advanced_init/footer_callback.html
The official documentation says that this callback will be fired only if there is a `<tfoot>` element in the markup.
I've tried to add it inside the Template.rendered callback - with no luck.
So, the question is - how could this be done?

**Comment by ephemer** [comment]
I don't know how to do this, but the standard Datatables API works as expected. In which case you could add a footer via Datatables' preferred methods (if there are some), or simply via jQuery. Closing this because it affects Datatables and not this package
