### ISSUE TITLE
Search box appears under Show dropdown, should be to the right of it.

### ISSUE THREAD

**Issue by mherb63** [ephemer/meteor-reactive-datatables#44]
Expected Behavior with zero configuration:

![image](https://cloud.githubusercontent.com/assets/1205814/23414025/88d5a298-fda8-11e6-8d2a-5c5f28ae1fcd.png)

What I'm seeing with this plugin:

![image](https://cloud.githubusercontent.com/assets/1205814/23414038/99950358-fda8-11e6-9d59-9df520ed29a5.png)

I would like the search box on the right like the first screen shot shows.  Is there a way to achieve this?

**Comment by ephemer** [comment]
Seems like you need to add bootstrap 3 to your project. Should look more as you expect after that, although you also have other custom styles. Or you may need to add the standard datatables css to your project

**Comment by ephemer** [comment]
Closing this because styling isn't the responsibility of this package
