### ISSUE TITLE
Using ID for datatable means you can't use more than one on the page!

### ISSUE THREAD

**Issue by ssteinerx** [ephemer/meteor-reactive-datatables#9]
<div id="datatable_wrapper"></div>

This makes it so that multiple reactive datatables can't be used on the same page.

If we could pass in the ID as a parameter, that would solve the problem, I think.

Thanks,

Steve

**Comment by ephemer** [comment]
I have pushed an update (1.0.4) that should fix this. I have allowed you to set a tableId in your options, and the datatable_wrapper is now a class instead of an ID.

**Comment by alisalaah** [comment]
I can't find where or how to do this (add custom id) and already tried peeking through the code.  Please help.

**Comment by rsercano** [comment]
I cant find the custom id option in the options as well... Maybe it's time to update your documentation ?

**Comment by rolivav** [comment]
+1, I can't find it either

**Comment by ephemer** [comment]
@rsercano @rolivav @alisalaah I am not actively using datatables at the moment but in my experience you don't need to set an ID, the underlying Datatables.js sets a unique one for you. What are you actually trying to achieve?

**Comment by rsercano** [comment]
We are trying to dynamically add events on the table... Currently not possible.

**Comment by ephemer** [comment]
@rsercano if I understand correctly you want to put DOM events on certain parts of your data tables. Adding events manually would very likely break every time your collection changes, but what you could do instead is use render callbacks in your datatableOptions (which fire, for example, every time the entire table, a (certain) page, row, column, cell is rendered – see DataTables docs), and add your events there. Remember to remove the eventListeners again when the content is destroyed or you may leak memory.

**Comment by rsercano** [comment]
Could you kindly please give me a code example with your package in meteor how to bind a click event on a <tr> tag ?

**Comment by ephemer** [comment]
@rsercano it depends what you're trying to do. See https://www.datatables.net/reference/event/ for the events. To access a specific datatable, use Meteor's onRendered callback and search for the datatable using `this.$(".datatable").on()`... The "this" will ensure you're accessing data table contained within that template.

**Comment by ephemer** [comment]
Alternatively use https://www.datatables.net/reference/option/ (look for callbacks on that page). You can pass these options into the datatableOptions object, the tender callbacks give you direct access to the datatable DOM, so you can do what you want with it

**Comment by alisalaah** [comment]
If there is more than one table in a template then we need to be able to
specify id in the options.

**Comment by rsercano** [comment]
@alisalaah exactly, main point was it sorry for misleading
